### PR TITLE
files added

### PR DESCRIPTION
**Pull request by SWAPNACHEMBOTH**
## General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work

### HTML

- [x] pages besides `/index.html` are stored in `/pages`
- [x] the code is well-formatted
- [x] the HTML is valid
- [x] there are no inline styles (example: `style='color: red;'`)
- [ ] there are no `<style>` tags with CSS, all styles are hrefs
- [ ] there is no inline JavaScript (example: `onclick='doSomething()'`)
- [ ] there are no `<script>` tags with JS, all JS is in an separate file
- [ ] `id`s are used for JavaScript only, not for CSS
- [x] semantic tags are used
- [x] spelling and grammar is correct in all site content

### CSS

- [x] the code is well-formatted
- [x] passes all the linting checks

### CODE REVIEW

**Review by TheRick88 — CHANGES_REQUESTED** [review]
Hello, good job but you are missing the students page footer.

**Comment by hadoan149** [comment]
Hi @SWAPNACHEMBOTH! It looks great however I noticed that:
- your branch is not up to date (could you please `git pull origin master `first?)
- There is still no embedded links to the social media icons
Let me know if you need further help

**Comment by TheRick88** [comment]
> Hi @SWAPNACHEMBOTH! It looks great however I noticed that:
> 
> * your branch is not up to date (could you please `git pull origin master `first?)
> * There is still no embedded links to the social media icons
>   Let me know if you need further help

@SWAPNACHEMBOTH Please follow the instructions from @hadoan149 regarding pulling before pushing to avoid merge conflicts like I showed you. Also add the links to the icons like we practiced this morning after that push so we can merge ur PR :)

**Review by TheRick88 — APPROVED** [review]
WELL DONE! :)

**Pull request merged**
